# Rust workspace tasks: Checks.

[tasks.check]
clear = true
dependencies = [
	"check-format",
	"check-docs",
	"check-workflows",
	"lint",
	"test",
]

[tasks.check-docs]
args = [
	"scripts/check-docs.py",
]
command = "python3"

[tasks.check-rust]
args = [
	"check",
	"--locked",
	"--workspace",
	"--all-targets",
	"--all-features",
]
command = "cargo"

[tasks.check-workflows]
args    = ["-color"]
command = "actionlint"
