# Formatting and format checks share the same scope.

[tasks.fmt]
dependencies = ["fmt-rust", "fmt-toml"]

[tasks.check-format]
dependencies = ["check-format-rust", "check-format-toml"]

[tasks.fmt-rust]
args    = ["run", "nightly", "cargo", "fmt", "--all"]
command = "rustup"

[tasks.check-format-rust]
args   = ["run", "nightly", "cargo", "fmt", "--all", "--", "--check"]
extend = "fmt-rust"

[tasks.fmt-toml]
args    = ["-c", "git ls-files -z --cached --others --exclude-standard -- '*.toml' | xargs -0 taplo fmt"]
command = "sh"

[tasks.check-format-toml]
args   = ["-c", "git ls-files -z --cached --others --exclude-standard -- '*.toml' | xargs -0 taplo fmt --check"]
extend = "fmt-toml"
