# Rust workspace tasks: Lint.

[tasks.lint]
dependencies = [
	"lint-rust",
	"lint-vstyle",
]

[tasks.lint-rust]
args = [
	"clippy",
	"--locked",
	"--all-features",
	"--all-targets",
	"--workspace",
	"--",
	"-D",
	"clippy::all",
	"-D",
	"clippy::too_many_lines",
	"-D",
	"clippy::unwrap_used",
	"-D",
	"clippy::use_self",
	"-D",
	"clippy::wildcard_imports",
	"-D",
	"missing-docs",
	"-D",
	"unused-crate-dependencies",
	"-D",
	"warnings",
]
command = "cargo"

[tasks.lint-vstyle]
dependencies = ["lint-vstyle-rust"]

[tasks.lint-vstyle-rust]
args = [
	"--locked",
	"vstyle",
	"curate",
	"--language",
	"rust",
	"--workspace",
	"--all-features",
	"--strict",
]
command = "cargo"
