# Rust workspace tasks: Lint Fix.

[tasks.lint-fix]
dependencies = [
	"lint-fix-rust",
	"lint-fix-vstyle",
]

[tasks.lint-fix-rust]
args = [
	"clippy",
	"--locked",
	"--fix",
	"--allow-dirty",
	"--all-features",
	"--all-targets",
	"--workspace",
	"--",
	"-D",
	"clippy::all",
	"-D",
	"clippy::too_many_lines",
	"-D",
	"clippy::unwrap_used",
	"-D",
	"clippy::use_self",
	"-D",
	"clippy::wildcard_imports",
	"-D",
	"missing-docs",
	"-D",
	"unused-crate-dependencies",
	"-D",
	"warnings",
]
command = "cargo"

[tasks.lint-fix-vstyle]
dependencies = ["lint-fix-vstyle-rust"]

[tasks.lint-fix-vstyle-rust]
args = [
	"--locked",
	"vstyle",
	"tune",
	"--language",
	"rust",
	"--workspace",
	"--all-features",
	"--strict",
]
command = "cargo"
