name: Language Checks

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  repo:
    name: Repository checks
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Fetch latest code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Rust CI tools
        uses: ./.github/actions/setup-rust
        with:
          checks: 'true'

      - name: Run repository checks
        run: cargo make check
